from .comandos import Execute

from stanfordkarel.stanfordkarel import (
    beepers_in_bag,
    beepers_present,
    facing_east,
    facing_north,
    facing_south,
    facing_west,
    front_is_blocked,
    front_is_clear,
    left_is_blocked,
    left_is_clear,
    move,
    no_beepers_in_bag,
    no_beepers_present,
    not_facing_east,
    not_facing_north,
    not_facing_south,
    not_facing_west,
    pick_beeper,
    put_beeper,
    right_is_blocked,
    right_is_clear,
    turn_left,
)
